#  ____  _            _______ _          _____
# |  _ \| |          |__   __| |        |  __ \
# | |_) | | __ _ _______| |  | |__   ___| |  | | _____   __
# |  _ <| |/ _` |_  / _ \ |  | '_ \ / _ \ |  | |/ _ \ \ / /
# | |_) | | (_| |/ /  __/ |  | | | |  __/ |__| |  __/\ V /
# |____/|_|\__,_/___\___|_|  |_| |_|\___|_____/ \___| \_/

# BlazinVanish Configuration File:
#  Use the § symbol for color coding
#   Default Config:
#     vanished-message: "§aYou have now been vanished"
#     unvanished-message: "§cYou have now been un-vanished"

# The message that will be sent to the player when they are vanished
vanished-message: "§aYou have now been vanished"

# The message that will be sent to the player when they are un-vanished
unvanished-message: "§cYou have now been un-vanished"